### PR TITLE
Different way to load files

### PR DESCRIPTION
**Pull request by inversebit**
Commit has the necessary info.
TL;DR: .clp file is packaged with the app.

For now this only works in the "SimpleDemo" example, I'll create future pull requests if I port this change to the other examples.

### CODE REVIEW

**Comment by gomezgoiri** [comment]
Thanks Inversebit.

Curiously this morning I have made a similar (the same?) change.

I'll check yours to merge the best of both approaches.

**Comment by inversebit** [comment]
Great. And thank **you** for this awesome project.

**Comment by inversebit** [comment]
Btw, I think this may solve #5.
I'll apply this patch to the AnimalDemo and let you know in the following days.

**Comment by gomezgoiri** [comment]
I've checked and my changes where equivalent to yours, but for the remaining two demo projects. I forgot updating the simple demo, so your pull request fits perfectly :-)

**Comment by gomezgoiri** [comment]
Regarding your last comment, just pull my last changes into your repo.

This morning  I made the very same change you talk about in AnimalDemo.

**Comment by inversebit** [comment]
Perfect

**Pull request merged**
